#!/usr/bin/env bash

BIN_DIRECTORY="./bin"

source "$BIN_DIRECTORY/helpers/color_helpers.sh"
source "$BIN_DIRECTORY/helpers/functions.sh"

# Handle differences between local and production environments
if [ "$1" == "prod" ]; then
    shift 1
    IS_PROD=true
    COMPOSE_FILE="docker-compose-prod.yml"
    ENV_FILE=".env.prod"
    LARAVEL_ENV_FILE="./laravel/.env.prod"
    ENTRY_SERVICE="web_app"
else
    IS_PROD=false
    COMPOSE_FILE="docker-compose.yml"
    ENV_FILE=".env"
    LARAVEL_ENV_FILE="./laravel/.env"
    ENTRY_SERVICE="nginx"
fi

# Make variables in the ENV_FILE accessible to the script
source "./${ENV_FILE}"


if [ $# -gt 0 ]; then
    COMMAND=$1
    shift 1

    COMMAND_FILE="$BIN_DIRECTORY/commands/$COMMAND.sh"
    if [ -f "$COMMAND_FILE" ]; then
        source "$COMMAND_FILE"
        command_run "$*"
    fi
else
    source "$BIN_DIRECTORY/commands/help.sh"
    command_run "$@"
fi