services:

  web:
    build:
      context: .
      dockerfile: web.dockerfile
      target: prod
      args:
        - PHP_VERSION=${PHP_VERSION}
        - NGINX_VERSION=${NGINX_VERSION}
        - APP_DOMAIN=${APP_DOMAIN}
        - CODE_REPO_URL=${CODE_REPO_URL}
        - ENV=${APP_ENVIRONMENT}
    ports:
      - "${HTTP_ON_HOST}:80"
      - "${HTTPS_ON_HOST}:443"
