services:

  web:
    build:
      target: dev
    container_name: ${APP_NAME}_${APP_ENVIRONMENT}
    depends_on:
      - mysql
      - redis
    volumes:
      - ./../../../code/${APP_NAME}:/var/www/html
    networks:
      - app_network

  mysql:
    #image: mariadb:${MARIADB_VERSION}
    image: arm64v8/mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}_mysql_${APP_ENVIRONMENT}
    ports:
      - ${MYSQL_ON_HOST}:3306
    volumes:
      - ./database/data/${APP_NAME}_data_${APP_ENVIRONMENT}:/var/lib/mysql
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${APP_NAME}_redis_${APP_ENVIRONMENT}
    ports:
      - ${REDIS_ON_HOST}:6379
    networks:
      - app_network

networks:
  app_network:
    name: ${APP_NAME}_${APP_ENVIRONMENT}
    driver: bridge


